((cmake-mode  . ((indent-tabs-mode . nil)))
 (c-mode  . ((tab-width . 4)
	     (c-basic-offset . 4)
	     (indent-tabs-mode . nil)
	     (fill-column . 210)
	     (c-file-style . "Linux")))

 (c++-mode  . ((tab-width . 4)
	      (c-basic-offset . 4)
	      (indent-tabs-mode . nil)
	      (fill-column . 210)
	      (c-file-style . "Linux")))
 (c++-ts-mode . ((tab-width . 4)
		 (c-ts-mode-indent-offset . 4)
		 (indent-tabs-mode . nil)))

 (glsl-mode . ((tab-width . 4)
	       (c-basic-offset . 4)
	       (indent-tabs-mode . nil)
	       (fill-column . 140)))
 (azsl-mode . ((tab-width . 4)
	       (c-basic-offset . 4)
	       (indent-tabs-mode . nil)
	       (fill-column . 1000)))
 (json-mode . ((indent-tabs-mode . nil)))
 )
